spring.application.name=document-service
server.servlet.context-path=/documents

server.port=8085

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/document_service
spring.datasource.username=postgres
spring.datasource.password=231205
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Connection Pooling (HikariCP, default in Spring Boot)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

kinga.app.jwtSecret= ======================Kinga=Spring===========================
kinga.app.jwtExpirationMs=86400000
kinga.documents.directory=${user.home}/kinga-storage/documents
